#!/usr/bin/env python
#%# family=auto
#%# capabilities=autoconf

import sys
import os

if "autoconf" in sys.argv:
    print "yes"
    exit(0)
elif "config" in sys.argv:
    print """
graph_title moe.py rated images size
graph_order rate1 rate2 rate3
graph_category misc
graph_args --base 1024 -l 0
graph_vlabel images size
rate1.label rating=1
rate1.draw AREA
rate2.label rating=2
rate2.draw STACK
rate3.label rating=3
rate3.draw STACK
total.label total
total.draw LINE1
"""
    exit(0)


import sqlite3

DB_CONN = sqlite3.connect("/home/santa/moe_pictures/moe.sqlite3", 5)
c = DB_CONN.cursor()

total = 0
for rate in range(1, 4):
    c.execute("select sum(file_size) from images where rating=%d" % rate)
    cnt = int(c.fetchone()[0])
    print "rate%s.value" % rate, cnt
    total += cnt

print "total.value", total
c.close()

