#!/usr/bin/env python
#%# family=auto
#%# capabilities=autoconf

import sys
import os

if "autoconf" in sys.argv:
    print "yes"
    exit(0)
elif "config" in sys.argv:
    print """
graph_title moe.py total images
graph_order danbooru danbooru_highres konachan konachan_highres moe_imouto moe_imouto_highres mypic nekobooru nekobooru_highres tu178
graph_category misc
graph_args --base 1000 -l 0
graph_vlabel images
danbooru.label danbooru
danbooru.draw AREA
danbooru_highres.label danbooru_highres
danbooru_highres.draw STACK
konachan.label konachan
konachan.draw STACK
konachan_highres.label konachan_highres
konachan_highres.draw STACK
moe_imouto.label moe_imouto
moe_imouto.draw STACK
moe_imouto_highres.label moe_imouto_highres
moe_imouto_highres.draw STACK
mypic.label mypic
mypic.draw STACK
nekobooru.label nekobooru
nekobooru.draw STACK
nekobooru_highres.label nekobooru_highres
nekobooru_highres.draw STACK
tu178.label tu178
tu178.draw STACK
total.label total
total.draw LINE1
"""
    exit(0)


import sqlite3

DB_CONN = sqlite3.connect("/home/santa/moe_pictures/moe.sqlite3", 5)
c = DB_CONN.cursor()

total = 0
for set_name in ["danbooru", "danbooru_highres", "konachan", "konachan_highres", "moe_imouto", "moe_imouto_highres", "mypic", "nekobooru", "nekobooru_highres", "tu178"]:
    c.execute("select count(*) from images where set_name='%s'" % set_name)
    cnt = int(c.fetchone()[0])
    print "%s.value" % set_name, cnt
    total += cnt

print "total.value", total
c.close()

