#!/bin/bash
# -*- sh -*-

: << =cut

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

STATS_FILE=/home/santa/.config/transmission/stats_shadow_copy.json

case $1 in
    autoconf)
    if [ -f $STATS_FILE ]; then
        echo yes
    else
        echo "no ($STATS_FILE not found)"
    fi
    exit 0
    ;;
    config)
    echo "graph_order down up" 
    echo "graph_title Transmission traffic"
    echo 'graph_args --base 1024'
    echo 'graph_vlabel bytes in (-) / out (+)'
    echo 'graph_category misc'
    echo 'down.label downloaded'
    echo 'down.type GAUGE'
    echo 'up.label uploaded'
    echo 'up.type GAUGE'
    echo 'up.negative down'
    exit 0
    ;;
esac

grep downloaded $STATS_FILE | gawk '{split($2, a, /,/); print "down.value " a[1]}'
grep uploaded $STATS_FILE | gawk '{split($2, a, /,/); print "up.value " a[1]}'

